site_name: SSCS Cluster Documentation
site_url: https://uchicago-ssd-sscs.github.io/hpc-docs
nav:
- Home: 'index.md'
- Getting Started: 
  - Overview: 'getting-started/overview.md'
  - Connecting to CVPN: 'getting-started/connect-to-vpn.md'
  - Accessing Cluster: 'getting-started/accessing-the-cluster.md'
  - Transferring Data: 'getting-started/data-transfer.md'
- Cluster Info:
  - Cluster Partitions: 'hardware/cluster-partitions.md'
  - Cluster Hardware: 'hardware/cluster-hardware-spec.md'
- Running Jobs:
  - Overview: 'jobs/overview.md'
  - Submitting Jobs: 'jobs/submitting-jobs.md'
  - Command Line Options: 'jobs/cli-options.md'
  - Creating First Sbatch Script: 'jobs/creating-your-first-sbatch-scripts.md'
- Software & Modules:
  - Overview: 'software/overview.md'
  - Modules: 'software/modules.md'
  - Conda: 'software/conda.md'
- FAQs: 'frequently-asked-questions.md'
# - Connecting: 'connecting/connecting.md'
# - Globus: 'globus/globus.md'
# - Slurm: 'slurm/slurm.md'
# - Software:
#   - Overview: 'software/overview.md'
#   - Modules: 'software/modules.md'
#   - Conda: 'software/conda.md'
# - Hardware: 'hardware/overview.md'

theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
extra_css:
  - assets/stylesheets/styles.css 

markdown_extensions:
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: "#"
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg