site_name: SSCS New Cluster
site_url: https://uchicago-ssd-sscs.github.io/hpc-docs
nav:
- Home: 'index.md'
- Getting Started: 
  - Overview: 'getting-started/overview.md'
  - Connecting to CVPN: 'getting-started/connect-to-vpn.md'
  - Accessing Cluster: 'getting-started/accessing-the-cluster.md'
  - Transferring Data: 'getting-started/data-transfer.md'
  - Basics of HPC Cluster: 'getting-started/basics-of-hpc-cluster.md'
  - Basics of SLURM: 'getting-started/basics-of-slurm.md'
- Cluster Info:
  - Cluster Partitions: 'hardware/cluster-partitions.md'
  - Cluster Hardware: 'hardware/cluster-hardware-spec.md'
  - Directory Structure: 'hardware/directory-structure.md'
- Running Jobs:
  - Overview: 'jobs/overview.md'
  - Submitting Jobs: 'jobs/submitting-jobs.md'
  - Command Line Options: 'jobs/cli-options.md'
  - Creating First Sbatch Script: 'jobs/creating-your-first-sbatch-scripts.md'
  - Monitoring & Managing Jobs: 'jobs/monitoring-and-managing-jobs.md'
  - Common Workflows: 'jobs/common-workflows.md'
- Software & Modules:
  - Overview: 'software/overview.md'
  - Modules: 'software/modules.md'
  - Conda Envrionment: 'software/conda.md'
- Globus: 
  - Overview: 'globus/overview.md'
  - Logging In to Globus: 'globus/logging-in-to-globus.md'
  - File Transfer with Globus: 'globus/file-transfer-with-globus.md'
- Advanced Workflows:
  - Ollama Guide: 'advanced-workflows/ollama-guide.md'
  - Jupyter via VSCode Guide: 'advanced-workflows/jupyter-notebook-via-vs-code.md'
  - VSCode via VNCViewer: 'advanced-workflows/vscode-via-vncviewer.md'
- FAQs: 'frequently-asked-questions.md'
- News & Announcements: 
  - Index: 'blog/index.md'
# - Connecting: 'connecting/connecting.md'
# - Slurm: 'slurm/slurm.md'
# - Hardware: 'hardware/overview.md'

theme:
  name: material
  logo: assets/icons/icon.png
  favicon: assets/icons/icon.ico
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.action.view
    - navigation.instant
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/stylesheets/styles.css
  - assets/stylesheets/footer.css

markdown_extensions:
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: "#"
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog:
      blog_dir: blog
      post_date_format: long
      authors: false
      archive: true
      archive_name: Archive
      archive_date_format: MMM yyyy
      archive_url_date_format: yyyy/MM
      categories: true
      categories_name: Category
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  generator: false

copyright: ""